# 工作流名称
name: .NET Publish and Package

# 触发工作流的事件
on:
  # 当有代码推送到 main 分支时触发
  push:
    branches: [ "main" ]
  # 当有 pull request 指向 main 分支时触发
  pull_request:
    branches: [ "main" ]
  # 允许您在 GitHub Actions 页面手动触发此工作流
  workflow_dispatch:

# 定义一个或多个作业（job）
jobs:
  build-and-publish:
    # 指定作业运行的虚拟机环境
    runs-on: windows-latest

    steps:
    # 第一步：检出（下载）你的仓库代码到虚拟机
    - name: Checkout repository
      uses: actions/checkout@v4

    # 第二步：安装和设置 .NET SDK 环境
    # 你可以根据你的项目需求更改 dotnet-version
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x # 推荐使用最新的稳定版，或你项目指定的版本

    # 第三步：还原 NuGet 包依赖
    - name: Restore dependencies
      run: dotnet restore AssemblyTool.sln

    # 第四步：发布项目 (这是关键的改动)
    # 使用 dotnet publish 会将所有需要的文件（包括依赖的DLL）都放到一个文件夹里
    # --configuration Release 表示发布为发行版
    # --output ./publish 指定一个统一的输出文件夹，方便后续打包
    - name: Publish project
      run: dotnet publish AssemblyTool.sln --configuration Release --no-restore --output ./publish

    # 第五步：上传发布产物
    # 现在我们只从 ./publish 这一个文件夹上传，里面包含了所有需要的文件
    - name: Upload publish artifacts
      uses: actions/upload-artifact@v4
      with:
        # 上传的产物包名称
        name: published-application
        # 要上传的文件路径，就是上面 publish 命令指定的输出目录
        path: ./publish
        # 产物保留天数
        retention-days: 7
