name: assembly-tool Release Build

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: '选择编译类型 (Select build type)'
        required: true
        default: 'Release'
        type: choice
        options:
        - Release
        - Debug
        - All

jobs:
  build-release:
    name: Build Release for Windows (win-x64)
    if: github.event.inputs.build_type == 'Release' || github.event.inputs.build_type == 'All'
    runs-on: windows-latest
    env:
      SOLUTION_FILE: 'AssemblyTool.sln'
      PROJECT_FILE: 'AssemblyTool/AssemblyTool.csproj'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore NuGet packages
        run: >
          dotnet restore ${{ env.SOLUTION_FILE }}
          --runtime win-x64

      - name: Generate Release File Name
        run: |
          $shortSha = git rev-parse --short HEAD
          $timestamp = Get-Date -Format "yyyyMMddHHmmss"
          echo "ARTIFACT_NAME=assembly-tool-release-win-x64-$shortSha-$timestamp" >> $env:GITHUB_ENV
        shell: powershell
        
      - name: Publish application
        run: >
          dotnet publish ${{ env.PROJECT_FILE }}
          --configuration Release
          --runtime win-x64
          --output ./Build/${{ env.ARTIFACT_NAME }}
          --no-restore
          -p:PublishSingleFile=true
          --self-contained true

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./Build/${{ env.ARTIFACT_NAME }}/

  build-debug:
    name: Build Debug for Windows (win-x64)
    if: github.event.inputs.build_type == 'Debug' || github.event.inputs.build_type == 'All'
    runs-on: windows-latest
    env:
      SOLUTION_FILE: 'AssemblyTool.sln'
      PROJECT_FILE: 'AssemblyTool/AssemblyTool.csproj'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore NuGet packages
        run: >
          dotnet restore ${{ env.SOLUTION_FILE }}
          --runtime win-x64

      - name: Generate Debug File Name
        run: |
          $shortSha = git rev-parse --short HEAD
          $timestamp = Get-Date -Format "yyyyMMddHHmmss"
          echo "ARTIFACT_NAME=assembly-tool-debug-win-x64-$shortSha-$timestamp" >> $env:GITHUB_ENV
        shell: powershell
        
      - name: Publish application
        run: >
          dotnet publish ${{ env.PROJECT_FILE }}
          --configuration Release
          --runtime win-x64
          --output ./Build/${{ env.ARTIFACT_NAME }}
          --no-restore
          -p:PublishSingleFile=true
          --self-contained true

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./Build/${{ env.ARTIFACT_NAME }}/
