# 工作流名称
name: .NET Publish and Package

# 触发工作流的事件
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-publish:
    # 指定作业运行的虚拟机环境
    runs-on: windows-latest

    steps:
    # 第一步：检出（下载）你的仓库代码到虚拟机
    - name: Checkout repository
      uses: actions/checkout@v4

    # 第二步：安装和设置 .NET SDK 环境
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        # 确保版本覆盖你项目中所有需要的 .NET 版本
        # .NET 8 SDK 可以编译旧的 .NET Framework 项目
        dotnet-version: 8.0.x

    # 第三步：还原 NuGet 包依赖
    - name: Restore dependencies
      run: dotnet restore AssemblyTool.sln

    # 第四步：发布项目 (这是关键的改动)
    # 添加 --framework net48 来解决多目标框架问题
    # 同时保留之前的 /p:PublishSingleFile=false 等参数
    - name: Publish project
      run: >
        dotnet publish AssemblyTool.sln 
        --configuration Release 
        --framework net48 
        --no-restore 
        --output ./publish 
        /p:PublishSingleFile=false 
        /p:PublishTrimmed=false

    # 第五步：上传发布产物
    - name: Upload publish artifacts
      uses: actions/upload-artifact@v4
      with:
        # 上传的产物包名称
        name: published-application
        # 要上传的文件路径
        path: ./publish
        # 产物保留天数
        retention-days: 7
