name: assembly-tool Release Build

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build Release for Windows (win-x64)
    runs-on: windows-latest

    env:
      SOLUTION_FILE: 'AssemblyTool.sln'
      PROJECT_FILE: 'AssemblyTool/AssemblyTool.csproj'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore NuGet packages
        run: >
          dotnet restore ${{ env.SOLUTION_FILE }}
          --runtime win-x64

      - name: Publish application
        run: >
          dotnet publish ${{ env.PROJECT_FILE }}
          --configuration Release
          --runtime win-x64
          --output ./Build/win-x64
          --no-restore
          -p:PublishSingleFile=true
          --self-contained true

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: assembly-tool-win-x64
          path: ./Build/win-x64
